#  Tema 2 

#### Termen de predare: 18 octombrie 2022, ora 20:00.

### Precizări

1. Se vor folosi **type annotations** pentru variabile, parametri tuturor funcțiilor, tipuri de retur. Se vor folosi **docstrings** pentru toate funcțiile. Neîndeplinirea acestei cerințe duce la înjumătățirea punctajului pentru exercițiul în cauză. 
1. Înainte de a trimite tema, verificați acoperirea cerințelor. 


### Conținut

1. Exercitii cu functii
1. Exercitii cu NumPy

## Execiții cu funcții:


 (1p) 1. Să se scrie o funcție care primește ca parametru un număr de 5 cifre. Să se returneze o listă cu toate numerele prime formate din cifrele parametrului.

In [71]:
from itertools import permutations

fiveDigitsNumber = 13579

def isPrime(nr:int) -> bool:
    '''This function shows if a integer number is prime or not.
    param nr: The number that will be searched if prime or not.
    for and if: Classic isPrime algorithm.
    '''
    for index in range(2,nr):
        if (nr%index) == 0:
              return False
    return True
    
def allPermutationList(number:int) -> str:
    '''This function will take all permutations of a 5 digits number,
    we will transform every permutation into a string of digits and put it in a list.
    Now, for every permutation we will construct a int number and if the number isPrime we add that permutation
    to a primeNumberList. At the end we print all the permutations from that list.
       param number: The 5 digits number from we make the permutations.  
    '''
    primeNumberList = []
    digitsList = []
    for index in str(number):
        digitsList.append(index)
    all_permutations = permutations(digitsList)
    for permutation in all_permutations:
        number_construction = 0
        for char in permutation:
            number_construction = number_construction * 10 + int(char)
        if isPrime(number_construction) == True:
            primeNumberList.append(number_construction)
    print(primeNumberList)

allPermutationList(fiveDigitsNumber)





[13597, 13759, 15739, 15937, 15973, 17359, 17539, 19753, 31957, 37159, 37591, 37951, 39157, 51973, 53197, 53719, 53791, 53917, 57139, 57193, 71359, 71593, 73951, 75193, 75391, 75913, 75931, 79153, 79531, 91573, 91753, 95317, 95713, 95731]


(1p) 2. Scrieți o funcție care primește ca parametru o frază de maxim 12 cuvinte și care returnează un tuplu ce conține doar cuvintele palindroame. Un palindrom este un șir de caractere care citit de la dreapta la stânga are același continut ca si citirea de la stanga la dreapta.

In [72]:
fraza = ["111", "iii", "1ii1"]
if len(fraza) > 12:
    print("Fraze has too many words.")
else:
    print("Fraze is ok.")
    
def isPalindrome(string: str) -> bool:
    """
    This function will return true if a string is Palindrome or False if it is not.
    param string: the string that we search if it is Palindrome or not.
    """
    return string == string[::-1]

def palindromWords(fraza: str) -> str:
    """
    This function wil take every word from a string of words and will use the isPalindrome function,
    if the word is a palindrom, it will be added to a tuple of palindrom words.
    param fraza: the input string of words.
    """
    tuplu1 = ()
    list_of_words = list(tuplu1)
    for cuvant in fraza:
        if isPalindrome(cuvant):
            list_of_words.append(cuvant)
    print(tuple(list_of_words))
    
palindromWords(fraza)
    

Fraze is ok.
('111', 'iii', '1ii1')


(1p) 3. Definiți o funcție care primește ca parametru o propoziție (string sau listă). Să se returneze un tuplu ce indică numărul de consoane, numărul de vocale și numărul de cifre din parametrul primit. Verificați dacă suma celor 3 valori formează un pătrat perfect.

In [85]:
import math
sentence = "0334AEINPP11111111111111$$$$ ."

def is_square(integer: int) -> int:
    """
    This function will return if an integer input number is perfect square or not.
    param integer: input number.
    """
    root = math.sqrt(integer)
# return integer == int(root + 0.5) ** 2
    return integer == int(root)**2

def numberOfConsVowelsAndDigits(sentence: str) -> None:
    """
    This function will count in different variables the number of vowels, consonant and digits.
    After that this data will be added into a tuple and the sum of the nr of vowels, consonants and digits
    will be searched if it is a perfect square with the is_square function. 
    If it is, the function will print "este patrat perfect.", else "nu este patrat perfect."
    """
    nrOfCons = 0
    nrOfVowels = 0
    nrOfDigits = 0
    sumOfCharacters = 0
    for character in sentence:
        if character.isalpha() == True:
            if(character =='A' or character =='E' or character =='I' or character =='O' or character =='U'
            or character =='a' or character =='e' or character =='i' or character =='o' or character =='u'):
                nrOfVowels+=1
            else:
                nrOfCons+=1
        if character.isdigit() == True:
            nrOfDigits+=1
            
    tuplu = (nrOfCons, nrOfVowels, nrOfDigits)
    sumOfCharacters = nrOfCons + nrOfVowels + nrOfDigits
    print("Tuplul este format din: ", tuplu, "consoane / vocale / cifre.")
    print("Suma lor este: ", sumOfCharacters, " iar aceasta ")
    if is_square(sumOfCharacters):
        print("este patrat perfect.")
    else:
        print("nu este patrat perfect.")
    
    
numberOfConsVowelsAndDigits(sentence)


    

Tuplul este format din:  (3, 3, 18) consoane / vocale / cifre.
Suma lor este:  24  iar aceasta 
nu este patrat perfect.


(1p) 4. Să se scrie o funcție recursivă care determină dacă un număr se poate descompune în sumă de numere consecutive.

In [75]:

def countConsecutive(number: int, suma: int, n: int) -> bool:
    """
    The algorithm work with the following formula: n + (n + 1) + (n + 2)...
    This function will return a bool result for a number.
    That result represents if the number can be divided in a sum of consecutive numbers or not.
    
    Case 1: input is a odd(impar) number then we know 100% we cand make a sum a two consecutive numbers:
    int(sum / 2) + (int(sum/2)) + 1.Function return TRUE.
    Case 2: input number is a event(par) number then the function will search
    if the (number - sum) remainder is zero this is also True for every situation, 
    the function will repeat this step as the formula from the top, until sum gets greater than the input,
    in that case we know that no consecutive numbers can be sumed into the input, and the function return FALSE. 
    """
    if number % 2 != 0:
        return True
        
    if (number - suma) % n == 0:
        return True
        
    if suma > number:
        return False
        
    return countConsecutive(number, suma + n, n + 1)
  

number = 12
seDescompune = countConsecutive(12, 1, 2)

if seDescompune == True:
    print("Numarul: ", number, "se poate descompune in suma de numere consecutive.",seDescompune)
else:
    print("Numarul: ", number, "NU se poate descompune in suma de numere consecutive.",seDescompune)

Numarul:  12 se poate descompune in suma de numere consecutive. True


In [2]:
# # Python program to count number of ways to
# # express N as sum of consecutive numbers.
 
# def countConsecutive(number:int) -> int:
     
#     # constraint on values of L gives us the
#     # time Complexity as O(N ^ 0.5)
#     count = 0
#     L = 1
#     while( L * (L + 1) < 2 * number):
#         a = (1.0 * number - (L * (L + 1) ) / 2) / (L + 1)
#         if (a - int(a) == 0.0):
#             count += 1
#         L += 1
#     return count
 
# # Driver code
 
# number = 15
# print (countConsecutive(number))
# number = 10
# print (countConsecutive(number))
 
# # This code is contributed by Sachin Bisht

3
1


In [61]:
# # aici am n-ul si imi face suma numerelor pana la n, ar trebui sa fac invers
# # am outputul ex. 15 1+2+3+4+5
# def recSum(sumOfNumbers, index = 1):
#     if sumOfNumbers - index >= 0:
# #         print(sumOfNumbers, " = ", sumOfNumbers, " - ", index, " = ", sumOfNumbers - index)
#         index += 1
#         return sumOfNumbers - recSum(sumOfNumbers - index)
#     else: return sumOfNumbers
    
# # def recursiveSum(number):
# #     if number <= 1:
# #         return number
# #     return number + recursiveSum(number - 1)
 
# # Driver code
# number = 15
# print(recSum(number))

## Probleme NumPy

(0.5 p) 1. Se dă un vector NumPy. Să se determine lista elementelor unice. Formați o matrice pătratică de dimensiune  `len(v)/2` care să conțină elementele unice din vector.
Completați cu cmmdc al elementelor unice pozițiile din matrice rămase libere.  

In [86]:
import numpy as np
from enum import unique

def cmmdc (a:int, b:int) -> int:
    """
    This function will return the greatest common factor between 2 integer numbers.
    param a,b: the input numbers.
    """
    if b == 0:
        return a
    else:
        return cmmdc(b, a%b)
    
def cmmdcFromUniqueElements(unique_elements: int) -> int:
    """
    This function will return the greatest common factor from an list of unique elements using the cmmdc function.
    Function will iterate from second position of list to the last one and will put in the element variable the result.
    At the end the function will return a integer number that is the cmmdc for the all elements in the list.
    param unique_elements: a list of integer numbers.
    """
    element = unique_elements[0]
    for index in range(1, len(unique_elements)):
        element = cmmdc(element, unique_elements[index])
    return element

def generateMatrix(matrix: np.ndarray, vector_np: np.ndarray, size_np: int, unique_elements: int, size: int, cmmdc: int):
    counter = 0
    
    for index1 in range(0, (size_np // 2) + 1):
        for index2 in range(0, (size_np // 2) + 1):
            matrix[index1, index2] = cmmdc
                        
    for index1 in range(0, (size_np // 2) + 1):
        for index2 in range(0, (size_np // 2) + 1):            
            if counter <= size - 1:
                matrix[index1, index2] = unique_elements[counter]
                counter += 1
            else:
                break



vector_np = np.ndarray([10,5,15,20,15,15,10])
size_np = np.size(vector_np.shape)
print("size = ", size_np)

vector = [10,5,15,20,15,15,10]
unique_elements = np.unique(vector)
print("unique element vector: ", unique_elements)
size = len(unique_elements)
print("size unique = ", size)
cmmdc_unique_elements = cmmdcFromUniqueElements(unique_elements)
print("cmmdc din unique elements este: ", cmmdc_unique_elements)

matrix = np.zeros(shape = (int(size_np / 2) + 1, int(size_np / 2) + 1), dtype = int)
print("matricea de zero: \n", matrix)


    
generateMatrix(matrix, vector_np, size_np, unique_elements, size, cmmdc_unique_elements)
print("matricea finala: \n", matrix)

size =  7
unique element vector:  [ 5 10 15 20]
size unique =  4
cmmdc din unique elements este:  5
matricea de zero: 
 [[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
matricea finala: 
 [[ 5 10 15 20]
 [ 5  5  5  5]
 [ 5  5  5  5]
 [ 5  5  5  5]]


(1.5 p) 2. Se dau punctele de forma `An(5n, 8n+1)`. 

a) Verificați dacă punctele `An-1`, `An`,`An+1` formează un triunghi. <br>
b) Verificați dacă punctele `A1`,`A2`,`An` sunt coliniare. <br>
c) Scrieți ecuația dreptei `A1A2`.
    
   **Indicație**: Puteți folosi noțiunea de determinant.

my name is geros


(1p) 3. Pentru o matrice de numere să se determine suma dintre minimul si maximul elementelor de pe linii sau de pe coloane, în funcție de valoarea unui parametru de tip boolean `compute_on_columns`.

In [91]:
import numpy as np
import random

def minimAndMaximSum (matrix: np.ndarray, compute_on_colomns: bool) -> None:
    """
    This function will calculate the sum of the list of every maximum and minimum from the every row or column
    depending on the compute_on_colomns input. If the input is False the function will compute on rows
    otherwise on columns.
    """
    print("Compute on columns = ", compute_on_colomns)
    
    
    maximum = np.amax(matrix, axis = int(not compute_on_colomns))
    minimum = np.amin(matrix, axis = int(not compute_on_colomns))
    suma = maximum + minimum
    print("axis= ", int(not compute_on_colomns), ": ", "amax: ", maximum, "amin:", minimum)
    print("suma: ", suma)
    suma = suma.sum()
    print("suma.sum(): ", suma)                
        
def generateMatrix(matrix: np.ndarray) -> None:
    """
    This function will assign random values to the matrix in the specified interval.
    """
    for index1 in range (0,matrix.shape[0]):                     
        for index2 in range (0, matrix.shape[1]):                   
            matrix[index1,index2] = random.randrange(0,21)
    print(matrix)  
    
 
matrix = np.zeros(shape = (3, 4), dtype = int)
generateMatrix(matrix)      
minimAndMaximSum(matrix, False)


[[ 5  7  2  0]
 [ 6  8 13  5]
 [17 13 14  6]]
Compute on columns =  False
axis=  1 :  amax:  [ 7 13 17] amin: [0 5 6]
suma:  [ 7 18 23]
suma.sum():  48


(1p) 4. Pentru un număr introdus de la tastaură, generați o matrice pătratică cu elemente aleatorii din intervalul `[0,2n]`. Calculați minimul elementelor de pe 
diagonala principală a matricei și maximul elementelor de pe diagonala secundară a matricei. Returnați rezultatele sub forma de tuplu.

In [133]:
import numpy as np
import random
def generateMatrix(matrix: np.ndarray, nRowColumns: int):
    """
    This function will generate a patratic matrix with a specific number of rows and columns,
    initialized with random numbers from randrange(start, finish)
    matrix param: is a np.ndarray matrix
    nRowColumns param: is a integer number representing the specific number of rows and columns. 
    """
    for index1 in range (0,matrix.shape[0]):                     
        for index2 in range (0, matrix.shape[1]):                   
            matrix[index1,index2] = random.randrange(0,21)
    print(matrix)
    

        
def minimAndMaximFromDiagonals(matrix: np.ndarray, nRowColumns: int):
    """
    This function will print the minim element from Principal Diagonal 
    and the maxim element from the Secondary Diagonal as a tuple.
    matrix param: is a np.ndarray matrix from wich we take the Principal and Secondary Diagonal Elements
    and add them into 2 vectors, one for PD elements and one for SD elements
    nRowColumns param: is a integer param that indicates the number of rows and columns.
    """
    principalDiagonalArray = np.zeros(shape = nRowColumns, dtype = int)
    secondaryDiagonalArray = np.zeros(shape = nRowColumns, dtype = int)
    minimPD = 0
    maximSD = 0
#     print("min: ", minimArray, " max: ", maximArray)
    
    for index in range (0, nRowColumns):
        principalDiagonalArray[index] = matrix[index,index] # pd
        
    for index in range (0, nRowColumns):
        secondaryDiagonalArray[index] = matrix[index,nRowColumns - index - 1] #sd
        
        
    minimPD = np.amin(principalDiagonalArray)
    maximSD = np.amax(secondaryDiagonalArray)
    minMaxTuple = (minimPD, maximSD)
    print ("\n minimPD: ", minMaxTuple, " :maximSD.")
#     print("min: ", minimPD, " max: ", maximSD)

          
nRowColumns = 3   
matrix = np.zeros(shape = (nRowColumns, nRowColumns), dtype = int)
generateMatrix(matrix,nRowColumns)
minimAndMaximFromDiagonals(matrix,nRowColumns)

[[20 14  3]
 [10  0 12]
 [ 8  9 14]]

 minimPD:  (0, 8)  :maximSD.


(2p) 5. Descarcați setul de date Wine descris la 'http://archive.ics.uci.edu/ml/datasets/Wine', fișierul `wine.data`, și încărcați-l într-o matrice NumPy, 
folosind `np.genfromtxt`. Alegeți aleator 28 de poziții din cadrul matricei de valori, setați pe aceste pozitii `NaN`.  Construiți o funcție care, 
primind la intrare o matrice, returnează o colecție cu indicii de linii respectiv de coloane în care se găsesc valori `NaN`, precum si matricea 'corectată':  valorile `NaN` se umplu cu o valoare ca parametru al funcției. 

In [94]:
import numpy as np
import random
from cmath import nan

def generateMatrix():
    """
    This function will generate a patratic matrix with a specific number of rows and columns,
    initialized with random numbers from randrange(start, finish)
    matrix param: is a np.ndarray matrix
    nRowColumns param: is a integer number representing the specific number of rows and columns. 
    """   
    matrix = np.genfromtxt("wine.data", delimiter = ",")
    return matrix

def changeRandomPositionsToNaN(matrix: np.ndarray) -> None:
    """
    This function will replace the element with NaN for a specified number of random locations
    """
    for count in range(1, 29):
        index1 = random.randrange(0, matrix.shape[0])
        index2 = random.randrange(0, matrix.shape[1])
        matrix[index1, index2] = nan        
        
def correctedMatrix(matrix: np.ndarray, replace_nan: int) -> None:
    """
    This function will replace the NaN elements with a specifed input and will add the position of that NaN value 
    into a list of tuples that will save every position of NaN values.
    """
    list_of_corrected_matrix = []
    for index1 in range(0, matrix.shape[0]):
        for index2 in range(0, matrix.shape[1]):
            if np.isnan(matrix[index1, index2]):
                list_of_corrected_matrix.append((index1, index2))
                matrix[index1, index2] = replace_nan
                print("Line = ", index1, " Column = ", index2, "is nan. ", matrix[index1, index2])
                
    print("\nMatricea corectata: \n", matrix)
    
    for index1 in range(0, matrix.shape[0]):
        for index2 in range(0, matrix.shape[1]):
            if np.isnan(matrix[index1, index2]):
                print("Este nan")
            else: 
                print("Nu este nan")
                
    return (list_of_corrected_matrix)
    
matrix=generateMatrix()
print(matrix, "\n")
changeRandomPositionsToNaN(matrix)
correctedMatrix(matrix, 3)

[[1.000e+00 1.423e+01 1.710e+00 ... 1.040e+00 3.920e+00 1.065e+03]
 [1.000e+00 1.320e+01 1.780e+00 ... 1.050e+00 3.400e+00 1.050e+03]
 [1.000e+00 1.316e+01 2.360e+00 ... 1.030e+00 3.170e+00 1.185e+03]
 ...
 [3.000e+00 1.327e+01 4.280e+00 ... 5.900e-01 1.560e+00 8.350e+02]
 [3.000e+00 1.317e+01 2.590e+00 ... 6.000e-01 1.620e+00 8.400e+02]
 [3.000e+00 1.413e+01 4.100e+00 ... 6.100e-01 1.600e+00 5.600e+02]] 

Line =  14  Column =  13 is nan.  3.0
Line =  26  Column =  8 is nan.  3.0
Line =  28  Column =  2 is nan.  3.0
Line =  33  Column =  0 is nan.  3.0
Line =  33  Column =  11 is nan.  3.0
Line =  34  Column =  5 is nan.  3.0
Line =  42  Column =  7 is nan.  3.0
Line =  49  Column =  3 is nan.  3.0
Line =  50  Column =  11 is nan.  3.0
Line =  84  Column =  2 is nan.  3.0
Line =  87  Column =  7 is nan.  3.0
Line =  88  Column =  6 is nan.  3.0
Line =  91  Column =  5 is nan.  3.0
Line =  109  Column =  11 is nan.  3.0
Line =  110  Column =  12 is nan.  3.0
Line =  115  Column =  8 is 

Nu este nan
Nu este nan
Nu este nan
Nu este nan
Nu este nan
Nu este nan
Nu este nan
Nu este nan
Nu este nan
Nu este nan
Nu este nan
Nu este nan
Nu este nan
Nu este nan
Nu este nan
Nu este nan
Nu este nan
Nu este nan
Nu este nan
Nu este nan
Nu este nan
Nu este nan
Nu este nan
Nu este nan
Nu este nan
Nu este nan
Nu este nan
Nu este nan
Nu este nan
Nu este nan
Nu este nan
Nu este nan
Nu este nan
Nu este nan
Nu este nan
Nu este nan
Nu este nan
Nu este nan
Nu este nan
Nu este nan
Nu este nan
Nu este nan
Nu este nan
Nu este nan
Nu este nan
Nu este nan
Nu este nan
Nu este nan
Nu este nan
Nu este nan
Nu este nan
Nu este nan
Nu este nan
Nu este nan
Nu este nan
Nu este nan
Nu este nan
Nu este nan
Nu este nan
Nu este nan
Nu este nan
Nu este nan
Nu este nan
Nu este nan
Nu este nan
Nu este nan
Nu este nan
Nu este nan
Nu este nan
Nu este nan
Nu este nan
Nu este nan
Nu este nan
Nu este nan
Nu este nan
Nu este nan
Nu este nan
Nu este nan
Nu este nan
Nu este nan
Nu este nan
Nu este nan
Nu este nan
Nu e

[(14, 13),
 (26, 8),
 (28, 2),
 (33, 0),
 (33, 11),
 (34, 5),
 (42, 7),
 (49, 3),
 (50, 11),
 (84, 2),
 (87, 7),
 (88, 6),
 (91, 5),
 (109, 11),
 (110, 12),
 (115, 8),
 (119, 6),
 (123, 7),
 (126, 11),
 (147, 8),
 (149, 0),
 (149, 7),
 (150, 7),
 (152, 4),
 (152, 11),
 (161, 0),
 (167, 8),
 (175, 10)]