# Laborator 3 - tema 3

* **Termen de predare: 26 octombrie 2022, ora 20:00**

Se vor folosi type annotations pentru variabile, parametrii tuturor funcțiilor, tipuri de retur. Se vor folosi docstrings pentru toate funcțiile. Neîndeplinirea acestei cerințe duce la înjumătățirea punctajului pentru exercițiul în cauză.  

Se acordă doua puncte din oficiu. Fișierul va fi denumit tema3_ia_nume_prenume.ipynb. Verificați înainte de trimitere faptul ca execuția celulelor de sus în jos funcționează corespunzător. Aserțiunile sunt obligatoriu a fi indeplinite. Suplimentar, puteti face verificari si pentru alte valori.

1. (1p) Pentru un vector de numere, care sunt toate pozitiile pe care apare valoarea minima?
Folositi functii NumPy.

In [1]:
import numpy as np
v = np.array([1, 2, 3, 4, 4, 3, 1] * 2, dtype=np.float32)  # de adnotat
print(v)
minimum = np.amin(v)
print(minimum)

positions_min = np.where(v == minimum)[0]
print(positions_min)

assert np.all(positions_min == [ 0,  6,  7, 13])

[1. 2. 3. 4. 4. 3. 1. 1. 2. 3. 4. 4. 3. 1.]
1.0
[ 0  6  7 13]


2. (1p) Construiti o functie care, primind o matrice, determina pe ce pozitii (linii, coloane) se afla valorile in intervalele [a, b] sau [c, d] date ca parametri. Functia va returna un tuplu de doi vectori: primul e cu indicii de linie, al doilea cu indicii de coloana unde se afla elementele cautate.

Exemplu:

In [2]:
import numpy as np
def pos_values(matrix: int, a: int, b: int, c: int, d: int) -> tuple:         # de adaugat typing annotations pentru parametri si tip de retur
    """
    This function will the positions for all the elements from the matrix that are between [a,b] and [c,d].
    We go through the matrix twice, first time for [a,b] interval and second one for the [c,d] interval.
    At the end we return as a tuple the 2 lists of indexes.
    matrix param: a matrix of integer numbers
    a,b,c,d params: int values that represent the [a,b] and [c,d] intervals.
    """
    rowIndex = []
    columnIndex = []
    for index1 in range(0,matrix.shape[0]):
        for index2 in range(0, matrix.shape[1]):
            if matrix[index1, index2] >= a and matrix[index1, index2] <= b:
                rowIndex.append(index1)
                columnIndex.append(index2)
                
    for index1 in range(0,matrix.shape[0]):
        for index2 in range(0, matrix.shape[1]):
            if matrix[index1, index2] >= c and matrix[index1, index2] <= d:
                rowIndex.append(index1)
                columnIndex.append(index2)
    
    rowColumnIndexes = (rowIndex, columnIndex)
    return rowColumnIndexes


    

# mat = pos_values(mat, 1, 2, 10, 15)
# print(mat)
mat = np.arange(12).reshape(3, 4)
rows, cols = pos_values(mat, 2, 4, 6, 8)
assert np.all(rows == [0, 0, 1, 1, 1, 2])
assert np.all(cols == [2, 3, 0, 2, 3, 0])
print(mat)
mat = pos_values(mat, 2, 4, 6, 8)
print(mat)
mat = -np.arange(12).reshape(3, 4)
rows, cols = pos_values(mat, 2, 4, 6, 8)
assert np.all(rows == [])
assert np.all(cols == [])
print(mat)
mat = pos_values(mat, 2, 4, 6, 8)
print(mat)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
([0, 0, 1, 1, 1, 2], [2, 3, 0, 2, 3, 0])
[[  0  -1  -2  -3]
 [ -4  -5  -6  -7]
 [ -8  -9 -10 -11]]
([], [])


3. (1p) Se da un vector cu numere intregi nenule. Sa se determine toti indicii `i` unde urmeaza o schimbare de semn. Codul se va scrie intr-o functie adnotata.

Exemplu: 
```python
v = [1, 2, -1, 2, 3, -1, 3, -10, -10, -10]
```
Trebuie sa rezulte vectorul de indici: `[1, 2, 4, 5, 6]`.

De luat in considerare ca:
1. Magnitudinea valorilor nu conteaza, doar semnele lor
1. Functia `where` gaseste indicii unde anumite proprietati sunt indeplinite

In [3]:
# [:-1] toate fara ultimul 
# [1:]toate fara primul
def jumping(v: np.array) -> int:  # de adnotat, doctstring
    """
    This function will return all the positions where will come next a sign change.
    We find these positions with np.where function and save the positions in an array.
    The frist np.sign() goes from index 0 to penultimety element and the second one goes
    from index 1 to the last element.
    v param: an array.
    """
    assert np.all( v != 0), 'All values should be non-zero'
#     positions = np.where(v[i] * v[i + 1] < 0)[0]
    positions = np.where(np.sign(v[:-1]) != np.sign(v[1:]))[0]
#     positions = np.where(v < 0, -1, +1)[0]
    print(positions)
    return positions

# test 1
v = np.array([1, 2, -1, 2, 3, -1, 3, -10, -10, -10])
print(v)
print("Test 1: ")
assert np.all(jumping(v) == [1, 2, 4, 5, 6])

# test 2: random vector, naive counting
v = np.random.randint(-100, 100, 1000)
print("Test 2: \n", v)
# patching 0 values
v[v==0] = -1
# naive way of counting jumps:
positions = []
for i in range(len(v)-1):
    if v[i] * v[i+1] < 0:
        positions.append(i)
    
assert np.all(positions == jumping(v))


[  1   2  -1   2   3  -1   3 -10 -10 -10]
Test 1: 
[1 2 4 5 6]
Test 2: 
 [  85   91  -82  -88   21  -47  -51  -54  -59  -27   49  -41   69  -81
   53   29   94  -96  -50   75  -81   35  -52   31   65  -61  -72  -49
   79   76   62  -22  -70   89  -90   41   67  -15  -69   19  -49  -59
  -88  -78    2   79   -9   28  -78   64   71  -44   41   92  -11  -45
   72  -19  -37   92  -27    3  -59  -76  -90   21  -74   43   89   43
   50  -38   68   38  -50  -73   33   51   -9  -54  -61  -93  -71   58
   -9   94    7    7   91  -38   36  -34   64   65  -64   -2    1   60
   73   39   -7  -21   28  -88   30   50   44  -94  -76   44  -26   78
    7  -43  -47  -37   88   58   12   83  -81  -59   58   35  -55  -67
   82  -93  -33  -48   46  -55  -76  -17   -6  -10   -2  -40   93   41
   20  -51   52   47   29   -3  -53    0  -10   23   84  -45   20   -6
   35  -52    2  -93   15 -100  -17  -11  -43   31  -90  -69  -68  -28
   55   59  -44   62   47  -22  -59   39  -12   98  -40  -11   -3   96
  -1

4. (1p) Generati o matrice aleatoare de dimensiune m*n care are m valori nan (not-an-number, https://numpy.org/doc/stable/reference/constants.html), la pozitii aleatoare. Determinati apoi suma elementelor non-nan din matrice in doua feluri (construiti doua functii). Comparati sumele returnate.

Exemplu:
```python
a = get_matrix(3, 4)
# sa presupunem ca a este
a = 
    1.5 2.2 np.nan
    4.3 np.nan np.nan
    10.1 5.0 -3.1
```

Suma elementelor este 20.0.
Indicatii: folositi functia `np.random.choice` cu parametri adecvati pentru a alege indici in mod aleator, fara repetare. 

In [4]:
import numpy as np
def get_matrix(m: int, n: int) -> np.array:          # de adnotat, docstring
    """
    This function will generate a matrix with random values and replace a specific number of m elements with
    nan value.
    """
    a = np.random.randn(m,n)
    a.ravel()[np.random.choice(a.size, m, replace=False)] = np.nan
    print(a)
    
            
    assert np.sum(np.isnan(a)) == m  # verificare: avem exact m nan-uri
    return a

def sum_1(a: np.array) -> float: 
    """
    This function will calculate the sum of all elements from matrix a, without nan values.
    """
    # de adnotat, docstring
    suma = np.sum(a[~np.isnan(a)])
    return suma

def sum_2(a: np.array) -> float: # de adnotat, docstring
    """
    This functio will calculate the sum of all elements from matrix a. Nan values are considered 0's.
    """
    suma = np.nansum(a)
    return suma

def naive_sum(a: np.ndarray) -> float:
    """
    This function will calculate the sum of all elements from matrix a, without nan values, they will be ignored.
    """
    s = 0
    m, n = a.shape
    for i in range(m):
        for j in range(n):
            s += a[i, j] if not np.isnan(a[i, j]) else 0
    return s

m = 3
n = 4
a = get_matrix(m,n)

suma1 = sum_1(a)
print("suma 1: ", suma1)
suma2 = sum_2(a)
print("suma 2: ", suma2)

rtol = 1e-05
atol = 1e-08

assert np.allclose(sum_1(a), naive_sum(a), rtol, atol)
assert np.allclose(sum_2(a), naive_sum(a), rtol, atol)

# pentru studenti: de ce e nevoie de allclose si nu se face comparatie cu == ?

[[ 1.40817913         nan -2.05779523  0.28723725]
 [-0.4813585   1.58264948  1.07411949         nan]
 [ 1.08882779  0.3863096          nan -1.32419468]]
suma 1:  1.9639743344472684
suma 2:  1.963974334447268


5. (1p) Folosnd functia `np.convolve`, sa se determine media alunecatoare (moving average) pentru un vector de 10000 de numere aleatoare; lungimea ferestrei alunecatore se da ca parametru al functiei construite de voi. Comparati rezultatele si viteza de executie cu a functiaie `naive_moving_average`.

Referinte:
1. [Moving average](https://en.wikipedia.org/wiki/Moving_average)
1. [np.convolve: How to Use Numpy convolve() Method](https://appdividend.com/2022/10/14/np-convolve/)

In [5]:
import numpy as np

def moving_average_fast(x: np.array, w: int) -> np.array:  # de adnotat, docstring
    """
    This function will calculate the moving average with convolve function, making it faster than mean function.
    """
    assert x.ndim == 1, 'One dimension numpy array'
    assert w > 1, 'Average of at least two values'
#     x2 = np.random.randint(w) ???
    x2 = np.ones(w)
    vect = np.convolve(x, x2, mode = 'valid') / w
    print(vect)
    return vect

def moving_average_slow(x: np.array, w: int) -> np.array: # de adnotat, docstring
    """
    This function will calculate the moving average with mean function (slower than convolve).
    """
    assert x.ndim == 1, 'One dimension numpy array'
    assert w > 1, 'Average of at least two values'
    result = np.zeros(x.shape[0]-w+1)
    for i in range(x.shape[0]-w+1):
        result[i] = np.mean(x[i:i+w])
    return result

len_vec, w = 10000, 10
x = np.random.rand(len_vec)

a = moving_average_fast(x, w)
b = moving_average_slow(x, w)

assert len(a) == len(b), 'The two methods should return vectors of the same lengths'
assert np.allclose(a, b), 'The two methods should return close vectors'

%timeit moving_average_fast(x, w)
%timeit moving_average_slow(x, w)

[0.50828702 0.49579159 0.45343814 ... 0.54570127 0.54773891 0.53769083]
[0.50828702 0.49579159 0.45343814 ... 0.54570127 0.54773891 0.53769083]
[0.50828702 0.49579159 0.45343814 ... 0.54570127 0.54773891 0.53769083]
[0.50828702 0.49579159 0.45343814 ... 0.54570127 0.54773891 0.53769083]
[0.50828702 0.49579159 0.45343814 ... 0.54570127 0.54773891 0.53769083]
[0.50828702 0.49579159 0.45343814 ... 0.54570127 0.54773891 0.53769083]
[0.50828702 0.49579159 0.45343814 ... 0.54570127 0.54773891 0.53769083]
[0.50828702 0.49579159 0.45343814 ... 0.54570127 0.54773891 0.53769083]
[0.50828702 0.49579159 0.45343814 ... 0.54570127 0.54773891 0.53769083]
[0.50828702 0.49579159 0.45343814 ... 0.54570127 0.54773891 0.53769083]
[0.50828702 0.49579159 0.45343814 ... 0.54570127 0.54773891 0.53769083]
[0.50828702 0.49579159 0.45343814 ... 0.54570127 0.54773891 0.53769083]
[0.50828702 0.49579159 0.45343814 ... 0.54570127 0.54773891 0.53769083]
[0.50828702 0.49579159 0.45343814 ... 0.54570127 0.54773891 0.53

[0.50828702 0.49579159 0.45343814 ... 0.54570127 0.54773891 0.53769083]
[0.50828702 0.49579159 0.45343814 ... 0.54570127 0.54773891 0.53769083]
[0.50828702 0.49579159 0.45343814 ... 0.54570127 0.54773891 0.53769083]
[0.50828702 0.49579159 0.45343814 ... 0.54570127 0.54773891 0.53769083]
[0.50828702 0.49579159 0.45343814 ... 0.54570127 0.54773891 0.53769083]
[0.50828702 0.49579159 0.45343814 ... 0.54570127 0.54773891 0.53769083]
[0.50828702 0.49579159 0.45343814 ... 0.54570127 0.54773891 0.53769083]
[0.50828702 0.49579159 0.45343814 ... 0.54570127 0.54773891 0.53769083]
[0.50828702 0.49579159 0.45343814 ... 0.54570127 0.54773891 0.53769083]
[0.50828702 0.49579159 0.45343814 ... 0.54570127 0.54773891 0.53769083]
[0.50828702 0.49579159 0.45343814 ... 0.54570127 0.54773891 0.53769083]
[0.50828702 0.49579159 0.45343814 ... 0.54570127 0.54773891 0.53769083]
[0.50828702 0.49579159 0.45343814 ... 0.54570127 0.54773891 0.53769083]
[0.50828702 0.49579159 0.45343814 ... 0.54570127 0.54773891 0.53

[0.50828702 0.49579159 0.45343814 ... 0.54570127 0.54773891 0.53769083]
[0.50828702 0.49579159 0.45343814 ... 0.54570127 0.54773891 0.53769083]
[0.50828702 0.49579159 0.45343814 ... 0.54570127 0.54773891 0.53769083]
[0.50828702 0.49579159 0.45343814 ... 0.54570127 0.54773891 0.53769083]
[0.50828702 0.49579159 0.45343814 ... 0.54570127 0.54773891 0.53769083]
[0.50828702 0.49579159 0.45343814 ... 0.54570127 0.54773891 0.53769083]
[0.50828702 0.49579159 0.45343814 ... 0.54570127 0.54773891 0.53769083]
[0.50828702 0.49579159 0.45343814 ... 0.54570127 0.54773891 0.53769083]
[0.50828702 0.49579159 0.45343814 ... 0.54570127 0.54773891 0.53769083]
[0.50828702 0.49579159 0.45343814 ... 0.54570127 0.54773891 0.53769083]
[0.50828702 0.49579159 0.45343814 ... 0.54570127 0.54773891 0.53769083]
[0.50828702 0.49579159 0.45343814 ... 0.54570127 0.54773891 0.53769083]
[0.50828702 0.49579159 0.45343814 ... 0.54570127 0.54773891 0.53769083]
[0.50828702 0.49579159 0.45343814 ... 0.54570127 0.54773891 0.53

[0.50828702 0.49579159 0.45343814 ... 0.54570127 0.54773891 0.53769083]
[0.50828702 0.49579159 0.45343814 ... 0.54570127 0.54773891 0.53769083]
[0.50828702 0.49579159 0.45343814 ... 0.54570127 0.54773891 0.53769083]
[0.50828702 0.49579159 0.45343814 ... 0.54570127 0.54773891 0.53769083]
[0.50828702 0.49579159 0.45343814 ... 0.54570127 0.54773891 0.53769083]
[0.50828702 0.49579159 0.45343814 ... 0.54570127 0.54773891 0.53769083]
[0.50828702 0.49579159 0.45343814 ... 0.54570127 0.54773891 0.53769083]
[0.50828702 0.49579159 0.45343814 ... 0.54570127 0.54773891 0.53769083]
[0.50828702 0.49579159 0.45343814 ... 0.54570127 0.54773891 0.53769083]
[0.50828702 0.49579159 0.45343814 ... 0.54570127 0.54773891 0.53769083]
[0.50828702 0.49579159 0.45343814 ... 0.54570127 0.54773891 0.53769083]
[0.50828702 0.49579159 0.45343814 ... 0.54570127 0.54773891 0.53769083]
[0.50828702 0.49579159 0.45343814 ... 0.54570127 0.54773891 0.53769083]
[0.50828702 0.49579159 0.45343814 ... 0.54570127 0.54773891 0.53

[0.50828702 0.49579159 0.45343814 ... 0.54570127 0.54773891 0.53769083]
[0.50828702 0.49579159 0.45343814 ... 0.54570127 0.54773891 0.53769083]
[0.50828702 0.49579159 0.45343814 ... 0.54570127 0.54773891 0.53769083]
[0.50828702 0.49579159 0.45343814 ... 0.54570127 0.54773891 0.53769083]
[0.50828702 0.49579159 0.45343814 ... 0.54570127 0.54773891 0.53769083]
[0.50828702 0.49579159 0.45343814 ... 0.54570127 0.54773891 0.53769083]
[0.50828702 0.49579159 0.45343814 ... 0.54570127 0.54773891 0.53769083]
[0.50828702 0.49579159 0.45343814 ... 0.54570127 0.54773891 0.53769083]
[0.50828702 0.49579159 0.45343814 ... 0.54570127 0.54773891 0.53769083]
[0.50828702 0.49579159 0.45343814 ... 0.54570127 0.54773891 0.53769083]
[0.50828702 0.49579159 0.45343814 ... 0.54570127 0.54773891 0.53769083]
[0.50828702 0.49579159 0.45343814 ... 0.54570127 0.54773891 0.53769083]
[0.50828702 0.49579159 0.45343814 ... 0.54570127 0.54773891 0.53769083]
[0.50828702 0.49579159 0.45343814 ... 0.54570127 0.54773891 0.53

[0.50828702 0.49579159 0.45343814 ... 0.54570127 0.54773891 0.53769083]
[0.50828702 0.49579159 0.45343814 ... 0.54570127 0.54773891 0.53769083]
[0.50828702 0.49579159 0.45343814 ... 0.54570127 0.54773891 0.53769083]
[0.50828702 0.49579159 0.45343814 ... 0.54570127 0.54773891 0.53769083]
[0.50828702 0.49579159 0.45343814 ... 0.54570127 0.54773891 0.53769083]
[0.50828702 0.49579159 0.45343814 ... 0.54570127 0.54773891 0.53769083]
[0.50828702 0.49579159 0.45343814 ... 0.54570127 0.54773891 0.53769083]
[0.50828702 0.49579159 0.45343814 ... 0.54570127 0.54773891 0.53769083]
[0.50828702 0.49579159 0.45343814 ... 0.54570127 0.54773891 0.53769083]
[0.50828702 0.49579159 0.45343814 ... 0.54570127 0.54773891 0.53769083]
[0.50828702 0.49579159 0.45343814 ... 0.54570127 0.54773891 0.53769083]
[0.50828702 0.49579159 0.45343814 ... 0.54570127 0.54773891 0.53769083]
[0.50828702 0.49579159 0.45343814 ... 0.54570127 0.54773891 0.53769083]
[0.50828702 0.49579159 0.45343814 ... 0.54570127 0.54773891 0.53

[0.50828702 0.49579159 0.45343814 ... 0.54570127 0.54773891 0.53769083]
[0.50828702 0.49579159 0.45343814 ... 0.54570127 0.54773891 0.53769083]
[0.50828702 0.49579159 0.45343814 ... 0.54570127 0.54773891 0.53769083]
[0.50828702 0.49579159 0.45343814 ... 0.54570127 0.54773891 0.53769083]
[0.50828702 0.49579159 0.45343814 ... 0.54570127 0.54773891 0.53769083]
[0.50828702 0.49579159 0.45343814 ... 0.54570127 0.54773891 0.53769083]
[0.50828702 0.49579159 0.45343814 ... 0.54570127 0.54773891 0.53769083]
[0.50828702 0.49579159 0.45343814 ... 0.54570127 0.54773891 0.53769083]
[0.50828702 0.49579159 0.45343814 ... 0.54570127 0.54773891 0.53769083]
[0.50828702 0.49579159 0.45343814 ... 0.54570127 0.54773891 0.53769083]
[0.50828702 0.49579159 0.45343814 ... 0.54570127 0.54773891 0.53769083]
[0.50828702 0.49579159 0.45343814 ... 0.54570127 0.54773891 0.53769083]
[0.50828702 0.49579159 0.45343814 ... 0.54570127 0.54773891 0.53769083]
[0.50828702 0.49579159 0.45343814 ... 0.54570127 0.54773891 0.53

[0.50828702 0.49579159 0.45343814 ... 0.54570127 0.54773891 0.53769083]
[0.50828702 0.49579159 0.45343814 ... 0.54570127 0.54773891 0.53769083]
[0.50828702 0.49579159 0.45343814 ... 0.54570127 0.54773891 0.53769083]
[0.50828702 0.49579159 0.45343814 ... 0.54570127 0.54773891 0.53769083]
[0.50828702 0.49579159 0.45343814 ... 0.54570127 0.54773891 0.53769083]
[0.50828702 0.49579159 0.45343814 ... 0.54570127 0.54773891 0.53769083]
[0.50828702 0.49579159 0.45343814 ... 0.54570127 0.54773891 0.53769083]
[0.50828702 0.49579159 0.45343814 ... 0.54570127 0.54773891 0.53769083]
[0.50828702 0.49579159 0.45343814 ... 0.54570127 0.54773891 0.53769083]
[0.50828702 0.49579159 0.45343814 ... 0.54570127 0.54773891 0.53769083]
[0.50828702 0.49579159 0.45343814 ... 0.54570127 0.54773891 0.53769083]
[0.50828702 0.49579159 0.45343814 ... 0.54570127 0.54773891 0.53769083]
[0.50828702 0.49579159 0.45343814 ... 0.54570127 0.54773891 0.53769083]
[0.50828702 0.49579159 0.45343814 ... 0.54570127 0.54773891 0.53

[0.50828702 0.49579159 0.45343814 ... 0.54570127 0.54773891 0.53769083]
[0.50828702 0.49579159 0.45343814 ... 0.54570127 0.54773891 0.53769083]
[0.50828702 0.49579159 0.45343814 ... 0.54570127 0.54773891 0.53769083]
[0.50828702 0.49579159 0.45343814 ... 0.54570127 0.54773891 0.53769083]
[0.50828702 0.49579159 0.45343814 ... 0.54570127 0.54773891 0.53769083]
[0.50828702 0.49579159 0.45343814 ... 0.54570127 0.54773891 0.53769083]
[0.50828702 0.49579159 0.45343814 ... 0.54570127 0.54773891 0.53769083]
[0.50828702 0.49579159 0.45343814 ... 0.54570127 0.54773891 0.53769083]
[0.50828702 0.49579159 0.45343814 ... 0.54570127 0.54773891 0.53769083]
[0.50828702 0.49579159 0.45343814 ... 0.54570127 0.54773891 0.53769083]
[0.50828702 0.49579159 0.45343814 ... 0.54570127 0.54773891 0.53769083]
[0.50828702 0.49579159 0.45343814 ... 0.54570127 0.54773891 0.53769083]
[0.50828702 0.49579159 0.45343814 ... 0.54570127 0.54773891 0.53769083]
[0.50828702 0.49579159 0.45343814 ... 0.54570127 0.54773891 0.53

[0.50828702 0.49579159 0.45343814 ... 0.54570127 0.54773891 0.53769083]
[0.50828702 0.49579159 0.45343814 ... 0.54570127 0.54773891 0.53769083]
[0.50828702 0.49579159 0.45343814 ... 0.54570127 0.54773891 0.53769083]
[0.50828702 0.49579159 0.45343814 ... 0.54570127 0.54773891 0.53769083]
[0.50828702 0.49579159 0.45343814 ... 0.54570127 0.54773891 0.53769083]
[0.50828702 0.49579159 0.45343814 ... 0.54570127 0.54773891 0.53769083]
[0.50828702 0.49579159 0.45343814 ... 0.54570127 0.54773891 0.53769083]
[0.50828702 0.49579159 0.45343814 ... 0.54570127 0.54773891 0.53769083]
[0.50828702 0.49579159 0.45343814 ... 0.54570127 0.54773891 0.53769083]
[0.50828702 0.49579159 0.45343814 ... 0.54570127 0.54773891 0.53769083]
[0.50828702 0.49579159 0.45343814 ... 0.54570127 0.54773891 0.53769083]
[0.50828702 0.49579159 0.45343814 ... 0.54570127 0.54773891 0.53769083]
[0.50828702 0.49579159 0.45343814 ... 0.54570127 0.54773891 0.53769083]
[0.50828702 0.49579159 0.45343814 ... 0.54570127 0.54773891 0.53

[0.50828702 0.49579159 0.45343814 ... 0.54570127 0.54773891 0.53769083]
[0.50828702 0.49579159 0.45343814 ... 0.54570127 0.54773891 0.53769083]
[0.50828702 0.49579159 0.45343814 ... 0.54570127 0.54773891 0.53769083]
[0.50828702 0.49579159 0.45343814 ... 0.54570127 0.54773891 0.53769083]
[0.50828702 0.49579159 0.45343814 ... 0.54570127 0.54773891 0.53769083]
[0.50828702 0.49579159 0.45343814 ... 0.54570127 0.54773891 0.53769083]
[0.50828702 0.49579159 0.45343814 ... 0.54570127 0.54773891 0.53769083]
[0.50828702 0.49579159 0.45343814 ... 0.54570127 0.54773891 0.53769083]
[0.50828702 0.49579159 0.45343814 ... 0.54570127 0.54773891 0.53769083]
[0.50828702 0.49579159 0.45343814 ... 0.54570127 0.54773891 0.53769083]
[0.50828702 0.49579159 0.45343814 ... 0.54570127 0.54773891 0.53769083]
[0.50828702 0.49579159 0.45343814 ... 0.54570127 0.54773891 0.53769083]
[0.50828702 0.49579159 0.45343814 ... 0.54570127 0.54773891 0.53769083]
[0.50828702 0.49579159 0.45343814 ... 0.54570127 0.54773891 0.53

[0.50828702 0.49579159 0.45343814 ... 0.54570127 0.54773891 0.53769083]
[0.50828702 0.49579159 0.45343814 ... 0.54570127 0.54773891 0.53769083]
[0.50828702 0.49579159 0.45343814 ... 0.54570127 0.54773891 0.53769083]
[0.50828702 0.49579159 0.45343814 ... 0.54570127 0.54773891 0.53769083]
[0.50828702 0.49579159 0.45343814 ... 0.54570127 0.54773891 0.53769083]
[0.50828702 0.49579159 0.45343814 ... 0.54570127 0.54773891 0.53769083]
[0.50828702 0.49579159 0.45343814 ... 0.54570127 0.54773891 0.53769083]
[0.50828702 0.49579159 0.45343814 ... 0.54570127 0.54773891 0.53769083]
[0.50828702 0.49579159 0.45343814 ... 0.54570127 0.54773891 0.53769083]
[0.50828702 0.49579159 0.45343814 ... 0.54570127 0.54773891 0.53769083]
[0.50828702 0.49579159 0.45343814 ... 0.54570127 0.54773891 0.53769083]
[0.50828702 0.49579159 0.45343814 ... 0.54570127 0.54773891 0.53769083]
[0.50828702 0.49579159 0.45343814 ... 0.54570127 0.54773891 0.53769083]
[0.50828702 0.49579159 0.45343814 ... 0.54570127 0.54773891 0.53

[0.50828702 0.49579159 0.45343814 ... 0.54570127 0.54773891 0.53769083]
[0.50828702 0.49579159 0.45343814 ... 0.54570127 0.54773891 0.53769083]
[0.50828702 0.49579159 0.45343814 ... 0.54570127 0.54773891 0.53769083]
[0.50828702 0.49579159 0.45343814 ... 0.54570127 0.54773891 0.53769083]
[0.50828702 0.49579159 0.45343814 ... 0.54570127 0.54773891 0.53769083]
[0.50828702 0.49579159 0.45343814 ... 0.54570127 0.54773891 0.53769083]
[0.50828702 0.49579159 0.45343814 ... 0.54570127 0.54773891 0.53769083]
[0.50828702 0.49579159 0.45343814 ... 0.54570127 0.54773891 0.53769083]
[0.50828702 0.49579159 0.45343814 ... 0.54570127 0.54773891 0.53769083]
[0.50828702 0.49579159 0.45343814 ... 0.54570127 0.54773891 0.53769083]
[0.50828702 0.49579159 0.45343814 ... 0.54570127 0.54773891 0.53769083]
[0.50828702 0.49579159 0.45343814 ... 0.54570127 0.54773891 0.53769083]
[0.50828702 0.49579159 0.45343814 ... 0.54570127 0.54773891 0.53769083]
[0.50828702 0.49579159 0.45343814 ... 0.54570127 0.54773891 0.53

[0.50828702 0.49579159 0.45343814 ... 0.54570127 0.54773891 0.53769083]
[0.50828702 0.49579159 0.45343814 ... 0.54570127 0.54773891 0.53769083]
[0.50828702 0.49579159 0.45343814 ... 0.54570127 0.54773891 0.53769083]
[0.50828702 0.49579159 0.45343814 ... 0.54570127 0.54773891 0.53769083]
[0.50828702 0.49579159 0.45343814 ... 0.54570127 0.54773891 0.53769083]
[0.50828702 0.49579159 0.45343814 ... 0.54570127 0.54773891 0.53769083]
[0.50828702 0.49579159 0.45343814 ... 0.54570127 0.54773891 0.53769083]
[0.50828702 0.49579159 0.45343814 ... 0.54570127 0.54773891 0.53769083]
[0.50828702 0.49579159 0.45343814 ... 0.54570127 0.54773891 0.53769083]
[0.50828702 0.49579159 0.45343814 ... 0.54570127 0.54773891 0.53769083]
[0.50828702 0.49579159 0.45343814 ... 0.54570127 0.54773891 0.53769083]
[0.50828702 0.49579159 0.45343814 ... 0.54570127 0.54773891 0.53769083]
[0.50828702 0.49579159 0.45343814 ... 0.54570127 0.54773891 0.53769083]
[0.50828702 0.49579159 0.45343814 ... 0.54570127 0.54773891 0.53

[0.50828702 0.49579159 0.45343814 ... 0.54570127 0.54773891 0.53769083]
[0.50828702 0.49579159 0.45343814 ... 0.54570127 0.54773891 0.53769083]
[0.50828702 0.49579159 0.45343814 ... 0.54570127 0.54773891 0.53769083]
[0.50828702 0.49579159 0.45343814 ... 0.54570127 0.54773891 0.53769083]
[0.50828702 0.49579159 0.45343814 ... 0.54570127 0.54773891 0.53769083]
[0.50828702 0.49579159 0.45343814 ... 0.54570127 0.54773891 0.53769083]
[0.50828702 0.49579159 0.45343814 ... 0.54570127 0.54773891 0.53769083]
[0.50828702 0.49579159 0.45343814 ... 0.54570127 0.54773891 0.53769083]
[0.50828702 0.49579159 0.45343814 ... 0.54570127 0.54773891 0.53769083]
[0.50828702 0.49579159 0.45343814 ... 0.54570127 0.54773891 0.53769083]
[0.50828702 0.49579159 0.45343814 ... 0.54570127 0.54773891 0.53769083]
[0.50828702 0.49579159 0.45343814 ... 0.54570127 0.54773891 0.53769083]
[0.50828702 0.49579159 0.45343814 ... 0.54570127 0.54773891 0.53769083]
[0.50828702 0.49579159 0.45343814 ... 0.54570127 0.54773891 0.53

[0.50828702 0.49579159 0.45343814 ... 0.54570127 0.54773891 0.53769083]
[0.50828702 0.49579159 0.45343814 ... 0.54570127 0.54773891 0.53769083]
[0.50828702 0.49579159 0.45343814 ... 0.54570127 0.54773891 0.53769083]
[0.50828702 0.49579159 0.45343814 ... 0.54570127 0.54773891 0.53769083]
[0.50828702 0.49579159 0.45343814 ... 0.54570127 0.54773891 0.53769083]
[0.50828702 0.49579159 0.45343814 ... 0.54570127 0.54773891 0.53769083]
[0.50828702 0.49579159 0.45343814 ... 0.54570127 0.54773891 0.53769083]
[0.50828702 0.49579159 0.45343814 ... 0.54570127 0.54773891 0.53769083]
[0.50828702 0.49579159 0.45343814 ... 0.54570127 0.54773891 0.53769083]
[0.50828702 0.49579159 0.45343814 ... 0.54570127 0.54773891 0.53769083]
[0.50828702 0.49579159 0.45343814 ... 0.54570127 0.54773891 0.53769083]
[0.50828702 0.49579159 0.45343814 ... 0.54570127 0.54773891 0.53769083]
[0.50828702 0.49579159 0.45343814 ... 0.54570127 0.54773891 0.53769083]
[0.50828702 0.49579159 0.45343814 ... 0.54570127 0.54773891 0.53

[0.50828702 0.49579159 0.45343814 ... 0.54570127 0.54773891 0.53769083]
[0.50828702 0.49579159 0.45343814 ... 0.54570127 0.54773891 0.53769083]
[0.50828702 0.49579159 0.45343814 ... 0.54570127 0.54773891 0.53769083]
[0.50828702 0.49579159 0.45343814 ... 0.54570127 0.54773891 0.53769083]
[0.50828702 0.49579159 0.45343814 ... 0.54570127 0.54773891 0.53769083]
[0.50828702 0.49579159 0.45343814 ... 0.54570127 0.54773891 0.53769083]
[0.50828702 0.49579159 0.45343814 ... 0.54570127 0.54773891 0.53769083]
[0.50828702 0.49579159 0.45343814 ... 0.54570127 0.54773891 0.53769083]
[0.50828702 0.49579159 0.45343814 ... 0.54570127 0.54773891 0.53769083]
[0.50828702 0.49579159 0.45343814 ... 0.54570127 0.54773891 0.53769083]
[0.50828702 0.49579159 0.45343814 ... 0.54570127 0.54773891 0.53769083]
[0.50828702 0.49579159 0.45343814 ... 0.54570127 0.54773891 0.53769083]
[0.50828702 0.49579159 0.45343814 ... 0.54570127 0.54773891 0.53769083]
[0.50828702 0.49579159 0.45343814 ... 0.54570127 0.54773891 0.53

[0.50828702 0.49579159 0.45343814 ... 0.54570127 0.54773891 0.53769083]
[0.50828702 0.49579159 0.45343814 ... 0.54570127 0.54773891 0.53769083]
[0.50828702 0.49579159 0.45343814 ... 0.54570127 0.54773891 0.53769083]
[0.50828702 0.49579159 0.45343814 ... 0.54570127 0.54773891 0.53769083]
[0.50828702 0.49579159 0.45343814 ... 0.54570127 0.54773891 0.53769083]
[0.50828702 0.49579159 0.45343814 ... 0.54570127 0.54773891 0.53769083]
[0.50828702 0.49579159 0.45343814 ... 0.54570127 0.54773891 0.53769083]
[0.50828702 0.49579159 0.45343814 ... 0.54570127 0.54773891 0.53769083]
[0.50828702 0.49579159 0.45343814 ... 0.54570127 0.54773891 0.53769083]
[0.50828702 0.49579159 0.45343814 ... 0.54570127 0.54773891 0.53769083]
[0.50828702 0.49579159 0.45343814 ... 0.54570127 0.54773891 0.53769083]
[0.50828702 0.49579159 0.45343814 ... 0.54570127 0.54773891 0.53769083]
[0.50828702 0.49579159 0.45343814 ... 0.54570127 0.54773891 0.53769083]
[0.50828702 0.49579159 0.45343814 ... 0.54570127 0.54773891 0.53

[0.50828702 0.49579159 0.45343814 ... 0.54570127 0.54773891 0.53769083]
[0.50828702 0.49579159 0.45343814 ... 0.54570127 0.54773891 0.53769083]
[0.50828702 0.49579159 0.45343814 ... 0.54570127 0.54773891 0.53769083]
[0.50828702 0.49579159 0.45343814 ... 0.54570127 0.54773891 0.53769083]
[0.50828702 0.49579159 0.45343814 ... 0.54570127 0.54773891 0.53769083]
[0.50828702 0.49579159 0.45343814 ... 0.54570127 0.54773891 0.53769083]
[0.50828702 0.49579159 0.45343814 ... 0.54570127 0.54773891 0.53769083]
[0.50828702 0.49579159 0.45343814 ... 0.54570127 0.54773891 0.53769083]
[0.50828702 0.49579159 0.45343814 ... 0.54570127 0.54773891 0.53769083]
[0.50828702 0.49579159 0.45343814 ... 0.54570127 0.54773891 0.53769083]
[0.50828702 0.49579159 0.45343814 ... 0.54570127 0.54773891 0.53769083]
[0.50828702 0.49579159 0.45343814 ... 0.54570127 0.54773891 0.53769083]
[0.50828702 0.49579159 0.45343814 ... 0.54570127 0.54773891 0.53769083]
[0.50828702 0.49579159 0.45343814 ... 0.54570127 0.54773891 0.53

[0.50828702 0.49579159 0.45343814 ... 0.54570127 0.54773891 0.53769083]
[0.50828702 0.49579159 0.45343814 ... 0.54570127 0.54773891 0.53769083]
[0.50828702 0.49579159 0.45343814 ... 0.54570127 0.54773891 0.53769083]
[0.50828702 0.49579159 0.45343814 ... 0.54570127 0.54773891 0.53769083]
[0.50828702 0.49579159 0.45343814 ... 0.54570127 0.54773891 0.53769083]
[0.50828702 0.49579159 0.45343814 ... 0.54570127 0.54773891 0.53769083]
[0.50828702 0.49579159 0.45343814 ... 0.54570127 0.54773891 0.53769083]
[0.50828702 0.49579159 0.45343814 ... 0.54570127 0.54773891 0.53769083]
[0.50828702 0.49579159 0.45343814 ... 0.54570127 0.54773891 0.53769083]
[0.50828702 0.49579159 0.45343814 ... 0.54570127 0.54773891 0.53769083]
[0.50828702 0.49579159 0.45343814 ... 0.54570127 0.54773891 0.53769083]
[0.50828702 0.49579159 0.45343814 ... 0.54570127 0.54773891 0.53769083]
[0.50828702 0.49579159 0.45343814 ... 0.54570127 0.54773891 0.53769083]
[0.50828702 0.49579159 0.45343814 ... 0.54570127 0.54773891 0.53

[0.50828702 0.49579159 0.45343814 ... 0.54570127 0.54773891 0.53769083]
[0.50828702 0.49579159 0.45343814 ... 0.54570127 0.54773891 0.53769083]
[0.50828702 0.49579159 0.45343814 ... 0.54570127 0.54773891 0.53769083]
[0.50828702 0.49579159 0.45343814 ... 0.54570127 0.54773891 0.53769083]
[0.50828702 0.49579159 0.45343814 ... 0.54570127 0.54773891 0.53769083]
[0.50828702 0.49579159 0.45343814 ... 0.54570127 0.54773891 0.53769083]
[0.50828702 0.49579159 0.45343814 ... 0.54570127 0.54773891 0.53769083]
[0.50828702 0.49579159 0.45343814 ... 0.54570127 0.54773891 0.53769083]
[0.50828702 0.49579159 0.45343814 ... 0.54570127 0.54773891 0.53769083]
[0.50828702 0.49579159 0.45343814 ... 0.54570127 0.54773891 0.53769083]
[0.50828702 0.49579159 0.45343814 ... 0.54570127 0.54773891 0.53769083]
[0.50828702 0.49579159 0.45343814 ... 0.54570127 0.54773891 0.53769083]
[0.50828702 0.49579159 0.45343814 ... 0.54570127 0.54773891 0.53769083]
[0.50828702 0.49579159 0.45343814 ... 0.54570127 0.54773891 0.53

[0.50828702 0.49579159 0.45343814 ... 0.54570127 0.54773891 0.53769083]
[0.50828702 0.49579159 0.45343814 ... 0.54570127 0.54773891 0.53769083]
[0.50828702 0.49579159 0.45343814 ... 0.54570127 0.54773891 0.53769083]
[0.50828702 0.49579159 0.45343814 ... 0.54570127 0.54773891 0.53769083]
[0.50828702 0.49579159 0.45343814 ... 0.54570127 0.54773891 0.53769083]
[0.50828702 0.49579159 0.45343814 ... 0.54570127 0.54773891 0.53769083]
[0.50828702 0.49579159 0.45343814 ... 0.54570127 0.54773891 0.53769083]
[0.50828702 0.49579159 0.45343814 ... 0.54570127 0.54773891 0.53769083]
[0.50828702 0.49579159 0.45343814 ... 0.54570127 0.54773891 0.53769083]
[0.50828702 0.49579159 0.45343814 ... 0.54570127 0.54773891 0.53769083]
[0.50828702 0.49579159 0.45343814 ... 0.54570127 0.54773891 0.53769083]
[0.50828702 0.49579159 0.45343814 ... 0.54570127 0.54773891 0.53769083]
[0.50828702 0.49579159 0.45343814 ... 0.54570127 0.54773891 0.53769083]
[0.50828702 0.49579159 0.45343814 ... 0.54570127 0.54773891 0.53

[0.50828702 0.49579159 0.45343814 ... 0.54570127 0.54773891 0.53769083]
[0.50828702 0.49579159 0.45343814 ... 0.54570127 0.54773891 0.53769083]
[0.50828702 0.49579159 0.45343814 ... 0.54570127 0.54773891 0.53769083]
[0.50828702 0.49579159 0.45343814 ... 0.54570127 0.54773891 0.53769083]
[0.50828702 0.49579159 0.45343814 ... 0.54570127 0.54773891 0.53769083]
[0.50828702 0.49579159 0.45343814 ... 0.54570127 0.54773891 0.53769083]
[0.50828702 0.49579159 0.45343814 ... 0.54570127 0.54773891 0.53769083]
[0.50828702 0.49579159 0.45343814 ... 0.54570127 0.54773891 0.53769083]
[0.50828702 0.49579159 0.45343814 ... 0.54570127 0.54773891 0.53769083]
[0.50828702 0.49579159 0.45343814 ... 0.54570127 0.54773891 0.53769083]
[0.50828702 0.49579159 0.45343814 ... 0.54570127 0.54773891 0.53769083]
[0.50828702 0.49579159 0.45343814 ... 0.54570127 0.54773891 0.53769083]
[0.50828702 0.49579159 0.45343814 ... 0.54570127 0.54773891 0.53769083]
[0.50828702 0.49579159 0.45343814 ... 0.54570127 0.54773891 0.53

[0.50828702 0.49579159 0.45343814 ... 0.54570127 0.54773891 0.53769083]
[0.50828702 0.49579159 0.45343814 ... 0.54570127 0.54773891 0.53769083]
[0.50828702 0.49579159 0.45343814 ... 0.54570127 0.54773891 0.53769083]
[0.50828702 0.49579159 0.45343814 ... 0.54570127 0.54773891 0.53769083]
[0.50828702 0.49579159 0.45343814 ... 0.54570127 0.54773891 0.53769083]
[0.50828702 0.49579159 0.45343814 ... 0.54570127 0.54773891 0.53769083]
[0.50828702 0.49579159 0.45343814 ... 0.54570127 0.54773891 0.53769083]
[0.50828702 0.49579159 0.45343814 ... 0.54570127 0.54773891 0.53769083]
[0.50828702 0.49579159 0.45343814 ... 0.54570127 0.54773891 0.53769083]
[0.50828702 0.49579159 0.45343814 ... 0.54570127 0.54773891 0.53769083]
[0.50828702 0.49579159 0.45343814 ... 0.54570127 0.54773891 0.53769083]
[0.50828702 0.49579159 0.45343814 ... 0.54570127 0.54773891 0.53769083]
[0.50828702 0.49579159 0.45343814 ... 0.54570127 0.54773891 0.53769083]
[0.50828702 0.49579159 0.45343814 ... 0.54570127 0.54773891 0.53

[0.50828702 0.49579159 0.45343814 ... 0.54570127 0.54773891 0.53769083]
[0.50828702 0.49579159 0.45343814 ... 0.54570127 0.54773891 0.53769083]
[0.50828702 0.49579159 0.45343814 ... 0.54570127 0.54773891 0.53769083]
[0.50828702 0.49579159 0.45343814 ... 0.54570127 0.54773891 0.53769083]
[0.50828702 0.49579159 0.45343814 ... 0.54570127 0.54773891 0.53769083]
[0.50828702 0.49579159 0.45343814 ... 0.54570127 0.54773891 0.53769083]
[0.50828702 0.49579159 0.45343814 ... 0.54570127 0.54773891 0.53769083]
[0.50828702 0.49579159 0.45343814 ... 0.54570127 0.54773891 0.53769083]
[0.50828702 0.49579159 0.45343814 ... 0.54570127 0.54773891 0.53769083]
[0.50828702 0.49579159 0.45343814 ... 0.54570127 0.54773891 0.53769083]
[0.50828702 0.49579159 0.45343814 ... 0.54570127 0.54773891 0.53769083]
[0.50828702 0.49579159 0.45343814 ... 0.54570127 0.54773891 0.53769083]
[0.50828702 0.49579159 0.45343814 ... 0.54570127 0.54773891 0.53769083]
[0.50828702 0.49579159 0.45343814 ... 0.54570127 0.54773891 0.53

85.2 ms ± 573 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)


6. (1p) Se dau vectorii de valori $x=[x_0 \dots x_{n-1}]$, $t=[t_0, \dots t_n-1]$, cu $t[0] < t[1] < \dots$. Sa se calculeze intr-o maniera vectorizata vectorul $v$ ale carui componente sunt:
$$
v[i] = \frac{x[i+1] - x[i]}{t[i+1] - t[i]}
$$

In prealabil sa se verifice (vectorizat sau functii NumPy) ca vectorul $t$ este format doar din valori strict crescatoare. Comparati rezultatele si viteza de executie cu o implementare care construieste vectorul $v$ pas cu pas.

Optional: incercati si o implementare folosind Numba. 

In [6]:
import numpy as np
from numba import jit

@jit
def is_increasing(t: np.array) -> bool:
    """This function will search if the array given as parameter is increasing. np.all() returns true 
    if all elements from the array are true.
    diff function return the difference between the elements of the array. 
    """
#     return all(x<y for x, y in zip(t, t[1:]))
    return np.all(np.diff(t) > 0)

    

@jit
def fast_v(x: np.array, t:np.array)->np.array:
    """This function assign values to an array based on the values of other arrays using a loop.
    @jit changes the function, making it faster than the usual (only works with numpy arrays and loops).
    """
    assert is_increasing(t), 'non increasing values'
    v = []
    for index in range(0, len(x) - 1):
        v.append((x[index + 1] - x[index])//(t[index + 1] - t[index]))
    return np.array(v)

def slow_v(x: np.array, t: np.array)->np.array:
    """This function is same as function as fast_v() but @jit is not used."""
    assert is_increasing(t), 'non increasing values'
    v = []
    for index in range(0, len(x) - 1):
        v.append((x[index + 1] - x[index])//(t[index + 1] - t[index]))
    return np.array(v)


    
n = 100000
x = np.random.rand(n)
t = np.random.randint(1, 10, n)
t = t.cumsum()
assert is_increasing(t), 't should be an increasing vector'
    
v1 = fast_v(x, t)
v2 = slow_v(x, t)
assert v1.shape == v2.shape
assert np.allclose(v1, v2)

%timeit fast_v(x, t)
%timeit slow_v(x, t)

1.91 ms ± 3.31 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)
95.6 ms ± 381 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)


7. (2p) Se da o matrice $a$ cu numere reale. 
    1. Sa se calculeze o alta matrice $b$ care are valorile calculate astfel:
    $$
    b[i, j] = \frac{a[i, j] - MIN}{MAX-MIN}
    $$
    unde $MAX$ si $MIN$ sunt valoarile minima, respectiv maxima din $a$. Tranformarea se face printr-o functie care preia o matrice si returneaza un tuplu compus din matricea $b$ si valorile $MIN$ si $MAX$ 
    2. Verificati ca in urma acestei transformari matricea $b$ are valorile in intervalul $(-epsilon, 1+epsilon)$, unde $epsilon=1e-5$.
    3. Daca se dau $b$, $MIN$, $MAX$, care este transfomarea inversa prin care obtinem matricea $a$ originara? Verificati ca valorile lui $a$ si $a_{reconstituit}$ sunt aproximativ egale. 

In [7]:
from typing import Tuple

import numpy as np
m, n = 100, 200

a = np.random.randn(m, n)

# rezolvare pct A
def min_max_scale(x: np.array) -> tuple: # de adnotat, docstring
    """
    This function will generate the b matrix with the following formula: 𝑏[𝑖,𝑗]=𝑎[𝑖,𝑗]−𝑀𝐼𝑁/𝑀𝐴𝑋−𝑀𝐼𝑁.
    """
    minim = x.min()
    maxim = x.max()
    b = (a - minim) / (maxim - minim) #
        
    print("matrice: \n", b, "\n nr minim: \n", minim, "\n nr minim: \n", maxim, "\n")
    return b, minim, maxim

# rezolvare pct B
def check_scaling(y: np.array, eps = 1e-5) -> bool: # de adnotat, docstring
    """
    This function will return true if all the elements from y array are between (- epsilon, 1 + epsilon) interval.
    If the minimum and maximum element are between that interval, all elements are between.
    """
    assert eps > 0
    minim = y.min()
    maxim = y.max()
    return -eps < minim and 1 + eps > maxim

assert check_scaling(min_max_scale(a)[0])

# rezolvare pct C
def inverse_min_max_scale(y: np.array, MIN: float, MAX: float): # de adnotat, docstring
    """
    This function will make a reconstitution of A matrix started from B matrix. If we start with this formula, 
    𝑏[𝑖,𝑗]=𝑎[𝑖,𝑗]−𝑀𝐼𝑁/𝑀𝐴𝑋−𝑀𝐼𝑁 we can find that a[i,j] = MIN + (y * (MAX - MIN)).
    y param: input array
    MIN, MAX params: float minim and maxim values from the array.
    """
    assert MAX > MIN
    a = MIN + (y * (MAX - MIN))
    print("Matricea reconstituita: \n", a)
    return a

b, MIN, MAX = min_max_scale(a)
print(MIN, MAX)
assert np.allclose(a, inverse_min_max_scale(b, MIN, MAX))

matrice: 
 [[0.14605414 0.57301882 0.28756633 ... 0.52936972 0.63667738 0.30285282]
 [0.49226945 0.63902739 0.51654539 ... 0.64808689 0.6332005  0.75122901]
 [0.71357339 0.400069   0.40437228 ... 0.58221981 0.49014067 0.42815503]
 ...
 [0.48424253 0.3487417  0.39288277 ... 0.58905765 0.34447765 0.2302013 ]
 [0.73638128 0.40620668 0.65942887 ... 0.49642326 0.72619363 0.4828078 ]
 [0.77656583 0.30069532 0.3457877  ... 0.75669529 0.26755202 0.46921547]] 
 nr minim: 
 -3.582124788285603 
 nr minim: 
 3.8392234410557142 

matrice: 
 [[0.14605414 0.57301882 0.28756633 ... 0.52936972 0.63667738 0.30285282]
 [0.49226945 0.63902739 0.51654539 ... 0.64808689 0.6332005  0.75122901]
 [0.71357339 0.400069   0.40437228 ... 0.58221981 0.49014067 0.42815503]
 ...
 [0.48424253 0.3487417  0.39288277 ... 0.58905765 0.34447765 0.2302013 ]
 [0.73638128 0.40620668 0.65942887 ... 0.49642326 0.72619363 0.4828078 ]
 [0.77656583 0.30069532 0.3457877  ... 0.75669529 0.26755202 0.46921547]] 
 nr minim: 
 -3.58212